#BUTTONS
b_release_confirm = "/html/body/div[2]/div[2]/div/div[1]/div/div[3]/button"
b_login="/html/body/div[2]/div[2]/div/div/form/input"
b_buy="/html/body/div/div/div[3]/div/div[1]/div/div[2]/div/div/div[1]/div[4]/div[3]/div/div/div[1]/div[1]/div[2]/div[1]"
b_paper_trade="/html/body/div/div/div[3]/div/div[1]/div/div[2]/div/div/div[1]/div[4]/div[3]/div/div/div[4]/button"
b_close_order_paper_trade="/html/body/div[2]/div[2]/div[2]/div[1]/div/div[6]/button"
b_possition_seleector="/html/body/div/div/div[3]/div/div[1]/div/div[2]/div/div/div[1]/div[7]/div[3]/div/div/div/div[1]/table/tbody/tr/td[1]"
b_all_selector="/html/body/div/div/div[3]/div/div[1]/div/div[2]/div/div/div[1]/div[6]/div[3]/div/div/div/div[1]/table/tbody/tr[1]/td[1]"
b_cancel_confirm="/html/body/div[2]/div[2]/div[3]/button[2]"
b_modify_paper_trade="/html/body/div[2]/div[2]/div[2]/div[1]/div/div[6]/button"
b_modify_close_dialogue="/html/body/div[2]/div[2]/div[1]/i"
b_continue_price_gap="/html/body/div[3]/div[2]/div[3]/button[2]"
b_continue_price_gap_last_limit="/html/body/div[2]/div[2]/div[3]/button[2]"
b_cancel_price_gap="/html/body/div[3]/div[2]/div[3]/button[1]"
b_ok_price_increment="/html/body/div[2]/div[2]/div[3]/button"


#ELEMENTS
e_login="/html/body/div/div/div[3]/div/div[1]/div/div[2]/div/div/div[1]/div[3]/div[3]/div/div"
e_uname="/html/body/div[2]/div[2]/div/div/form/div[2]/div[1]/div/input"
e_all_section="/html/body/div/div/div[3]/div/div[1]/div/div[2]/div/div/div[1]/div[6]/div[1]/div/div/div/div/div[5]"
e_ticker_1_txt="/html/body/div/div/div[3]/div/div[1]/div/div[2]/div/div/div[1]/div[2]/div[3]/div/div[2]/div/div[2]/div/li[1]/div[2]/div[1]/div[1]/span[1]"
e_ticker_2_txt="/html/body/div/div/div[3]/div/div[1]/div/div[2]/div/div/div[1]/div[2]/div[3]/div/div[2]/div/div[2]/div/li[2]/div[2]/div[1]/div[1]/span[1]"
e_ticker_3_txt="/html/body/div/div/div[3]/div/div[1]/div/div[2]/div/div/div[1]/div[2]/div[3]/div/div[2]/div/div[2]/div/li[3]/div[2]/div[1]/div[1]/span[1]"
e_ticker_1_price="/html/body/div/div/div[3]/div/div[1]/div/div[2]/div/div/div[1]/div[2]/div[3]/div/div[2]/div/div[2]/div/li[1]/div[2]/div[2]/div[1]"
e_ticker_2_price="/html/body/div/div/div[3]/div/div[1]/div/div[2]/div/div/div[1]/div[2]/div[3]/div/div[2]/div/div[2]/div/li[2]/div[2]/div[2]/div[1]"
e_ticker_3_price="/html/body/div/div/div[3]/div/div[1]/div/div[2]/div/div/div[1]/div[2]/div[3]/div/div[2]/div/div[2]/div/li[3]/div[2]/div[2]/div[1]"
e_ticker_1_lst ="/html/body/div/div/div[3]/div/div[1]/div/div[2]/div/div/div[1]/div[2]/div[3]/div/div[2]/div/div[2]/div/li[1]"
e_ticker_2_lst ="/html/body/div/div/div[3]/div/div[1]/div/div[2]/div/div/div[1]/div[2]/div[3]/div/div[2]/div/div[2]/div/li[2]"
e_ticker_3_lst ="/html/body/div/div/div[3]/div/div[1]/div/div[2]/div/div/div[1]/div[2]/div[3]/div/div[2]/div/div[2]/div/li[3]"
e_volume="/html/body/div/div/div[3]/div/div[1]/div/div[2]/div/div/div[1]/div[4]/div[3]/div/div/div[1]/div[2]/div[2]/div[2]/div/input"
e_price="/html/body/div/div/div[3]/div/div[1]/div/div[2]/div/div/div[1]/div[4]/div[3]/div/div/div[1]/div[3]/div/div[2]/div[1]/input"
e_close_order="/html/body/div[2]/div[1]/div"
e_close_order_vol="/html/body/div[2]/div[2]/div[2]/div[1]/div/div[3]/div[2]/div[2]/div[2]/div/input"
e_close_order_price="/html/body/div[2]/div[2]/div[2]/div[1]/div/div[3]/div[3]/div/div[2]/div[1]/input"
e_filled_time="/html/body/div/div/div[3]/div/div[1]/div/div[2]/div/div/div[1]/div[6]/div[3]/div/div/div/div[1]/table/tbody/tr[1]/td[7]"
e_cancel="/html/body/div[2]/div[2]/div"
e_modify="/html/body/div[2]/div[1]/div"
e_modify_price="/html/body/div[2]/div[2]/div[2]/div[1]/div/div[3]/div[2]/div/div[2]/div[1]/input"